modmap:
  - name: Left Thumb
    remap:
      KEY_LEFTALT:
        held: KEY_F1 #Media
        alone: KEY_ESC
      KEY_LEFTMETA:
        held: KEY_F2 #Fun
        alone: KEY_TAB
      KEY_SPACE:
        held: KEY_F3 #Nav
        alone: KEY_SPACE
  - name: Right Thumb
    remap:
      KEY_RIGHTALT:
        held: KEY_F4 #Sym
        alone: KEY_ENTER
      KEY_RIGHTCTRL:
        held: KEY_F5 #Num
        alone: KEY_BACKSPACE
  - name: Left Home Row
    remap:
      KEY_A:
        held: KEY_LEFTALT
        alone: KEY_A
      KEY_S:
        held: KEY_LEFTALT
        alone: KEY_S
      KEY_D:
        held: KEY_LEFTCTRL
        alone: KEY_D
      KEY_F:
        held: KEY_LEFTSHIFT
        alone: KEY_F
  - name: Right Home Row
    remap:
      KEY_J:
        held: KEY_LEFTSHIFT
        alone: KEY_J
      KEY_K:
        held: KEY_LEFTCTRL
        alone: KEY_K
      KEY_L:
        held: KEY_LEFTALT
        alone: KEY_L
      KEY_SEMICOLON:
        held: KEY_LEFTALT
        alone: KEY_SEMICOLON
keymap:
  - name: Layer one
    remap:
