modmap:
  - name: custom modmap
    remap:
      KEY_CAPSLOCK: KEY_ESC
      KEY_RIGHTALT: KEY_ENTER
      KEY_RIGHTCTRL: KEY_BACKSPACE
      KEY_LEFTALT: KEY_LEFTCTRL
      KEY_LEFTCTRL: KEY_LEFTALT
keymap:
  - name: custom binding
    remap:
      C-h: left
      C-l: right
      C-k: up
      C-j: down
      KEY_FN-KEY_U: KEY_1
      KEY_FN-KEY_I: KEY_2
      KEY_FN-KEY_O: KEY_3
      KEY_FN-KEY_J: KEY_4
      KEY_FN-KEY_K: KEY_5
      KEY_FN-KEY_L: KEY_6
      KEY_FN-KEY_M: KEY_7
      KEY_FN-KEY_COMMA: KEY_8
      KEY_FN-KEY_DOT: KEY_9
